name: version, tag and github release

on:
  push:
    branches:
      - main
      - prerelease/*
    tags-ignore:
      - '*'

jobs:
  release:
    uses: salesforcecli/github-workflows/.github/workflows/githubRelease.yml@main
    secrets: inherit
    with:
      prerelease: ${{ github.ref_name != 'main' }}
  docs:
    uses: salesforcecli/github-workflows/.github/workflows/publishTypedoc.yml@main
    secrets: inherit
    needs: release
