name: publish source-deploy-retrieve-bundle
on:
  workflow_call:
    inputs:
      branch:
        description: 'Set the branch to use for release'
        type: string
        required: false
        default: 'main'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Set the branch to use for release'
        type: string
        required: false
        default: 'main'

jobs:
  call-release-workflow:
    if: ${{ inputs.branch }}
    uses: forcedotcom/bundle-publish-scripts/.github/workflows/releaseWithCoreBundle.yml@main
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}
